baseURL = "https://infosecvandana.com/"
languageCode = "en-us"
title = "Vandana Verma"

publishDir = "docs"

theme = "personal-web"
copyright="© Vandana Verma"

[params.intro]
  main = "Vandana Verma"
  sub = "Security Leader"

[params.main]
  latestPublishHeader = "My Project"

[params]
  breadcrumb = false
  accentColor = "#FD3519"
  mainSections = ['post'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "404 not found"

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/background_blue.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  #logo = "/images/vandana_headshot.jpeg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/vermava"
  twitter = "https://twitter.com/infosecvandana"
  linkedin = "https://www.linkedin.com/in/vandana-verma"
  youtube = "https://www.youtube.com/channel/UCyr-gas4Un-3YBEDIUQtNjg"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "talks"
  name = "Conference Talks"
  title = "Blog section"
  url = "/talks/"
  weight = -100

[[menu.main]]
  identifier = "blog"
  name = "Blogs"
  title = "Blog section"
  url = "/blogs/"
  weight = -90

[[menu.main]]
  identifier = "trainings"
  name = "Trainings"
  title = "Trainings section"
  url = "/trainings/"
  weight = -80

[[menu.main]]
  identifier = "featured"
  name = "Featured"
  title = "featured section"
  url = "/featured/"
  weight = -70

[[menu.main]]
  identifier = "Awards"
  name = "Awards"
  title = "Awards"
  url = "/awards/"
  weight = -40

[[menu.main]]
  identifier = "webinars"
  name = "Webinars"
  title = "webinars"
  url = "/webinars/"
  weight = -60

[[menu.main]]
  identifier = "paneldiscussion"
  name = "Panel Discussion"
  title = "Panel Discussion"
  url = "/paneldiscussion/"
  weight = -50

[[menu.main]]
  identifier = "advisoryboard"
  name = "Advisory Board"
  title = "Advisory Board"
  url = "/advisoryboard/"
  weight = -40

[[menu.main]]
  identifier = "Podcasts"
  name = "Podcasts"
  title = "Podcasts"
  url = "/Podcasts/"
  weight = -50

[[menu.main]]
  identifier = "leaderspeak"
  name = "A Day in the life of an Entrepreneur"
  title = "Leader Speak - A Day in the life of an Entrepreneur"
  url = "/leaderspeak/"
  weight = -30

[[menu.main]]
  identifier = "ciso"
  name = "A Day in the life of a CISO"
  title = "Leader Speak - A Day in the life of a CISO"
  url = "/ciso/"
  weight = -20

[[menu.main]]
  identifier = "owaspspotlightseries"
  name = "OWASP Projects Spotlight Series"
  title = "OWASP Projects Spotlight Series"
  url = "/owaspspotlightseries/"
  weight = -20
  
[[menu.main]]
  identifier = "books"
  name = "Books Authored or Contributed"
  title = "Books Authored or Contributed"
  url = "/books/"
  weight = -10

[[menu.main]]
  identifier = "judge"
  name = "Awards Judge or Jury"
  title = "Awards Judge or Jury"
  url = "/judge/"
  weight = -10

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
